### PR TITLE
MEF plugin set-up and demo git plugin.

### PR DESCRIPTION
**Pull request by ddurschlag**
The goal of this change is to allow the use of SourceBrowser while supplementing its index with other information about the codebase being indexed. The change itself has three main components:

1) The first is the addition of an MEF project, which contains interfaces for building plugins to SourceBrowser. Plugins are able to write small chunks of HTML next to relevant lines. This project also contains some basic MEF scaffolding to keep it out of the main code.

2) Changes to the main code to load and execute plugins.

3) An example plugin which checks if a project is part of a git repo and, if so, adds blame information, with links to email authors about their changes.

The interface for plugins has allows two approaches: text-oriented (line by line), and symbol-oriented. An argument for a syntax-oriented plugin is possible, but I couldn't come up with a significant use-case for it. The symbol plugin is not used in the example, however I have used it for an internal plugin (to integrate with our error tracking system) and can confirm it is functional.

### CODE REVIEW

**Comment by ddurschlag** [comment]
Sorry, just noticed there IS a bug in the symbol-based functionality. I'll be fixing that shortly. The git plugin is unaffected.

**Comment by KirillOsenkov** [comment]
Thanks for this! There are very minor stylistic issues but it seems OK overall.

General theme:
1. field names start with lowecase
2. parameter names start with lowercase
3. single statements inside other statements should always be enclosed in { and } and followed by an empty line (unless at end of method body)
4. sort and remove usings (check option 'Place System on top')
5. format document (Ctrl+E,D or Ctrl+K,D depending on your VS profile)

I honestly haven't tried to understand the algorithmic change but I trust that if it looks good for you then it must be OK.

**Comment by ddurschlag** [comment]
Took another pass at the standards listed. Let me know if anything still looks off.

**Comment by KirillOsenkov** [comment]
Thanks!

**Pull request merged**
