### PR TITLE
Omit 'Web Access' link for files untracked by most gitignores

### LINKED ISSUE #169: Could 'Web Access' be hidden for untracked sources?
Anything that `<EmbedUntrackedSources>` would affect should not get a 'Web Access' link:

image

### PR DESCRIPTION
**Pull request by jnm2**
Closes #169

File with `obj` path segment:

image

File without `obj` path segment:

image

### CODE REVIEW

**Comment by jnm2** [comment]
@KirillOsenkov This was the last thing I was planning to look into in the near future.

**Comment by KirillOsenkov** [comment]
Published https://www.nuget.org/packages/SourceBrowser/1.0.35.

Thanks for stopping by and do come and visit us again sometime!

**Comment by jnm2** [comment]
@KirillOsenkov I won't hesitate if I think of something. Will source.dot.net etc pick up the new build? It would improve the dark mode arrows.

**Comment by KirillOsenkov** [comment]
@alexperovich merges into his fork periodically, so hopefully in the near future

**Comment by jnm2** [comment]
Either something is wrong with my robocopy /MIR or I didn't actually fix dark mode arrows properly (all the other changes came through):

image

**Comment by KirillOsenkov** [comment]
Try https://github.com/KirillOsenkov/ContentSync, but _carefully_ read the command-line help first :)

It was made precisely for the task of incrementally copying Index directories.

**Comment by KirillOsenkov** [comment]
Also check the browser cache or server cache maybe.

**Comment by jnm2** [comment]
Clearing my browser cache fixed it.

**Pull request merged**
